# Estágio 1: Configurando o ambiente de desenvolvimento Django
FROM python:3.9 AS django-backend

ARG postgres_host=''

ENV PYTHONUNBUFFERED=1
ENV POSTGRES_HOST ${postgres_host}

RUN echo "starting build"

# Define o diretório de trabalho para o serviço backend
WORKDIR /service

# Copia os arquivos de dependências do Django
COPY requirements.txt .

# Instala as dependências do Django
RUN pip install --upgrade pip && pip install -r requirements.txt gunicorn

# Copia o código fonte do Django
COPY . .

# Expõe a porta 8000 para o servidor Django
EXPOSE 80

COPY entrypoint.sh /service/entrypoint.sh
RUN chmod +x /service/entrypoint.sh

ENTRYPOINT [ "/service/entrypoint.sh" ]